name: followupapprefactored
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"
#--------------- PACKAGES ------------------#
dependencies:
  analyzer: ^6.4.1
  awesome_notifications: ^0.9.2
  build_runner: ^2.4.7
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  day_night_switch: ^1.0.4
  day_night_switcher: ^0.2.0+1
  dio: ^5.4.3+1
  dropdown_search: ^5.0.6
  encrypt: ^5.0.3
  equatable: ^2.0.5
  eva_icons_flutter: ^3.1.0
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_cache_manager_dio: ^4.0.0
  flutter_image_compress: ^2.1.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^17.1.2
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  flutter_offline: ^3.0.1
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.1.0
  fluttertoast: ^8.2.4
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  get_storage: ^2.1.1
  go_router: ^14.2.3
  google_nav_bar: ^5.0.6
  googleapis_auth: ^1.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.1.0
  icons_flutter: ^0.0.4
  iconsax: ^0.0.8
  image_cropper: ^7.0.4
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  material_design_icons_flutter: ^7.0.7296
  oauth_dio: ^0.2.9
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.0
  pretty_dio_logger: ^1.3.1
  response: ^1.0.0
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  shared_preferences: ^2.2.1
  smooth_page_indicator: ^1.1.0
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/.
    - assets/lang/.
    - assets/logos/.
    - assets/icons/brands/
    - assets/images/.
    - assets/images/excersiseImages/
    - assets/images/content/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
  #--------------- LOCAL FONTS ------------------#
fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800
  - family: MyCustomIcons
    fonts:
      - asset: assets/fonts/MyCustomIcons.ttf
